name: structured_logger
description: Another logging package, but for structured logging, with the concept of sinks for log output
version: 0.0.2
homepage: https://github.com/Altamir/structured_logger

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

 