name: structured_logger_dio_interceptor
description: Dio interceptor emitting structured Log Events via pre-configured StructureLogger.
version: 1.4.0-DEV.0
homepage: https://github.com/Altamir/structured_logger
repository: https://github.com/Altamir/structured_logger

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  structured_logger: ^1.0.4-DEV.0
  dio: ^5.1.1
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.8
  lints: ^6.0.0
  http: ^1.2.2
